#!/bin/sh

# Use neovim for vim if present.
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d"

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	mkd="mkdir -pv" \
	yt="youtube-dl --add-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	recordff="ffmpeg -f x11grab -s 1020x1080 -i :0.0" \
	ffmpeg="ffmpeg -hide_banner" \
	pacuni="doas pacman -Rns" \
	config="/usr/bin/git --git-dir=$HOME/dotfiles --work-tree=$HOME" \
	dmenu_h="dmenu -h 40" \
	rss="$TERMINAL -e newsboat"

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi"

# alias for vm toggle
alias \
	winstart="virsh -c qemu:///system start winvm" \
	winstop="virsh -c qemu:///system stop winvm"
