#!/bin/sh
slstatus 2>&1 >/dev/null &
picom &
mpd &
#feh --bg-fill -z "$WALLPAPERS" &
xwallpaper --zoom $(find $WALLPAPERS -type f | shuf -n 1) &
xrdb "${XDG_CONFIG_HOME:-$HOME/.config}"/x11/xresources &
unclutter &
dunst &
pamixer --set-volume 25 &
xautolock -time 45 -locker slock &
