#!/bin/sh
picom --no-fading-openclose &
feh --bg-fill -z ~/.local/share/Wallpapers &
sxhkd &
unclutter &
dunst &
setxkbmap -options caps:escape &
amixer sset Master 25% &
statusbar &
xautolock -time 20 -locker slock &
